
#define VMA_VULKAN_VERSION 1004000  
#define VMA_DEDICATED_ALLOCATION 1 
#define VMA_BIND_MEMORY2 1         
#define VMA_MEMORY_BUDGET 1        
#define VMA_EXTERNAL_MEMORY 1      
#define VMA_EXTERNAL_MEMORY_WIN32 1
#define VMA_BUFFER_DEVICE_ADDRESS 1 
#define VMA_MEMORY_PRIORITY 1
#define VMA_KHR_MAINTENANCE4 1
#define VMA_KHR_MAINTENANCE5 1
#define VK_USE_PLATFORM_WIN32_KHR

#include <vk_mem_alloc.h>
