module test_generator.gen_cimgui;

import std.stdio    : writefln;
import std.process  : environment;
import std.string   : endsWith;

import ec.parse.stmt.Stmt;
import ec.parse.stmt.Typedef;
import ec.all;

import common       : StringBuffer;
import common.utils : getSuffix;

/**
 * Download cimgui docking branch:
 *   cd C:/pvmoore/cpp/
 *   git clone --recursive https://github.com/cimgui/cimgui.git 
 *   git checkout docking_inter
 *   (may also need to "git submodule update --init --recursive")
 *
 * To update to the latest imgui submodule:
 *   git pull
 *   git submodule update --recursive
 *
 * In imgui/imconfig.h, uncomment these to disable obsolete functions:
 *   #define IMGUI_DISABLE_OBSOLETE_FUNCTIONS
 *   #define IMGUI_DISABLE_OBSOLETE_KEYIO   <-- this one may now be obsolete
 *
 * Update the Vulkan SDK path in .\cimgui\CimguiLib\CimguiLib.sln
 * Build the visual studio solution to generate the DLL. 
 * Rename the CimguiLib.dll to cimgui-glfw-vk-VERSION.dll and copy to the dlls folder and to the vulkan libs folder.
 *
 * Update the version 'imguiVersion' below.
 * Run this processor.
 * Copy generated/cimgui_api.d to where it is used. 
 * Copy the DLL to where it is used.
 */
void generateCimgui() {
    writefln("Generating Cimgui API...");

    enum version_      = "1.92.8";
    enum name          = "CImgui";
    enum dllName       = "cimgui-glfw-vk-%s.dll".format(version_);
    enum dllNameDebug  = "cimgui-glfw-vk-%s-debug.dll".format(version_);

    auto headerText = 
"module cimgui_api;

public:

// CImgui %s include file converted to D (This is a generated file)
//
// (https://github.com/cimgui/cimgui)
// 
// Generated by Echo-C (https://github.com/pvmoore/echo-c)
// 
// Usage:
//     CImguiLoader.load();
//     ** 
//     ** Use cimgui functions here
//     ** 
//     CImguiLoader.unload();
".format(version_);

    enum footerText =
"
struct ImVector(T) {
    import core.stdc.string : memcpy;
    
    int                 Size;
    int                 Capacity;
    T*                  Data;

    void clear() { if (Data) { Size = Capacity = 0; igMemFree(Data); Data = null; } }
    bool empty() { return Size == 0; }

    void push_back(T* v) { if (Size == Capacity) reserve(_grow_capacity(Size + 1)); memcpy(&Data[Size], v, T.sizeof); Size++; }

    void reserve(int new_capacity) {
        if (new_capacity <= Capacity) return; T* new_data = cast(T*)igMemAlloc(cast(size_t)new_capacity * T.sizeof); if (Data) { memcpy(new_data, Data, cast(size_t)Size * T.sizeof); igMemFree(Data); } Data = new_data; Capacity = new_capacity;
    }

    int _grow_capacity(int sz) { int new_capacity = Capacity ? (Capacity + Capacity / 2) : 8; return new_capacity > sz ? new_capacity : sz; }

    void swap(ref ImVector!T rhs) { 
        int rhs_size = rhs.Size; rhs.Size = Size; Size = rhs_size; 
        int rhs_cap = rhs.Capacity; rhs.Capacity = Capacity; Capacity = rhs_cap; 
        T* rhs_data = rhs.Data; rhs.Data = Data; Data = rhs_data; 
    }

    int size_in_bytes() { return cast(int)(Size * T.sizeof); }

    void resize(int new_size) { if (new_size > Capacity) reserve(_grow_capacity(new_size)); Size = new_size; }

    T* erase_unsorted(T* it) { 
		assert(it >= Data && it < Data + Size);  
		ptrdiff_t off = it - Data; 
		if(it < Data + Size - 1) memcpy(Data + off, Data + Size - 1, T.sizeof); 
		Size--; 
		return Data + off; 
	}

    ref T opIndex(ulong i) {
		return Data[i];
	}
	int opApply(int delegate(ref T value) dg) {
        foreach(i; 0..Size) {
            T value = Data[i];
            int result = dg(value);
            if(result) return result;
        }
        return 0;
    }
	int opApply(int delegate(int index, ref T value) dg) {
        foreach(i; 0..Size) {
            T value = Data[i];
            int result = dg(i, value);
            if(result) return result;
        }
        return 0;
    }
}
struct ImPool(T) {
    ImVector!T      Buf;        // Contiguous data
    ImGuiStorage    Map;        // ID->Index
    ImPoolIdx       FreeIdx;    // Next free idx to use
    ImPoolIdx       AliveCount; // Number of active/alive items (for display purpose)
}
struct ImChunkStream(T) {
    ImVector!char  Buf;
}
struct ImSpan(T) {
    T*                  Data;
    T*                  DataEnd;
}
struct ImVec2_c {
    float x;
    float y;

    ImVec2 opBinary(string op)(ImVec2 a) if (op==\"+\" || op==\"-\") {
        static if (op == \"+\") {
            return ImVec2(x+a.x, y+a.y);
        }
        static if (op == \"-\") {
            return ImVec2(x-a.x, y-a.y);
        }
    }
}
alias va_list = immutable(char)*;

//================================================================================================
// (Since 1.92)
//================================================================================================
ImGuiIO* igGetIO() { return igGetIO_Nil(); }
ImGuiIO* igGetIO(ImGuiContext* ctx) { return igGetIO_ContextPtr(ctx); }

ImGuiPlatformIO* igGetPlatformIO() { return igGetPlatformIO_Nil(); }
ImGuiPlatformIO* igGetPlatformIO(ImGuiContext* ctx) { return igGetPlatformIO_ContextPtr(ctx); }
";

    auto stmtGenerator = new class IStmtGenerator {
        ReturnType doGenerate(Stmt stmt, APIEmitter base) {
            if(Struct st = stmt.as!Struct) {

                // These have been converted to templates (see foot text above)
                const TEMPLATES = [
                    "ImVector_",
                    "ImPool_",
                    "ImChunkStream_",
                    "ImSpan_",
                ];
                foreach(t; TEMPLATES) {
                    if(st.name.startsWith(t)) {
                        return ReturnType(true, null);
                    }
                }

                // Ignore these
                switch(st.name) {
                    case "ImVec2_c": 
                    case "ImVec2":
                    case "ImVec2i":
                    case "ImVec4":
                    case "ImColor":
                        return ReturnType(true, null);
                    default: break;
                }
            }

            return ReturnType(false, "");
        }
    };
    ITypeGenerator typeGenerator = new class ITypeGenerator {
        ReturnType doGenerate(Type type, APIEmitter base) {
            if(auto tr = type.as!TypeRef) {

                // These have been converted to templates (see foot text above)
                const TEMPLATES = [
                    "ImVector",
                    "ImPool",
                    "ImChunkStream",
                    "ImSpan",
                ];
                foreach(t; TEMPLATES) {
                    if(tr.name.startsWith(t ~ "_")) {
                        auto suffix = tr.name.getSuffix("_");

                        switch(suffix) {
                            case "const_charPtr": suffix = "(char)"; break;
                            case "unsigned_char": suffix = "ubyte"; break;
                            case "const_char": suffix = "char"; break;

                            default: 
                                if(suffix.endsWith("Ptr")) {
                                    suffix = "(%s*)".format(suffix[0..$-3]);
                                }
                                break;
                        }

                        string result = "%s!%s%s".format(t, suffix, type.getPtrString());

                        return ReturnType(true, result);
                    }
                }
            }
            return ReturnType(false, null); 
        }
    };

    auto emitter = new APIEmitter(name)
        .addLoaderGenerator(new DLLLoaderGenerator("CImguiLoader", dllName, dllNameDebug))
        .addStmtGenerator(stmtGenerator)
        .addTypeGenerator(typeGenerator)
        .setHeaderText(headerText)
        .setFooterText(footerText)
        .setExcludePrefixes([])
        .setAliasPrefixes(["Im", "stbrp_"])
        .setTypePrefixes(["Im", "stbrp_", "STB"])
        .setFunctionPrefixes(["ig", "Im"])
        ;

    Config conf = {
        sourceDirectory: "resources/large-tests/",
        targetDirectory: ".target/test-cimgui/",
        includeDirectories: [
            "C:/pvmoore/cpp/cimgui/"
        ],
        emitter: emitter
    };
    
    EC ec = new EC(conf);

    ec.addCFile("test_cimgui.c");
    ec.generate();

    writefln("  Done");
}
