module test_generator.gen_ktx;

import std.stdio    : writefln;
import std.process  : environment;
import std.string   : endsWith;

import ec.parse.stmt.Stmt;
import ec.parse.stmt.Typedef;
import ec.all;

import common       : StringBuffer;
import common.utils : getSuffix;

void generateKtx() {
    writefln("Generating KTX API...");

    enum version_      = "5.0.0";
    enum name          = "KTX";
    enum dllName       = "ktx-%s.dll".format(version_);
    enum dllNameDebug  = "ktx-%s-debug.dll".format(version_);

    auto headerText = 
"module ktx_api;

private import vulkan.api.vulkan_api;
private import core.stdc.stdio : FILE;

public:

// KTX-Software %s include file converted to D (This is a generated file)
//
// (https://github.com/khronosgroup/ktx-software)
// 
// Generated by Echo-C (https://github.com/pvmoore/echo-c)
// 
// Usage:
//     if(KTXLoader.load()) {
//         ** 
//         ** Use KTX functions here
//         ** 
//         KTXLoader.unload();
//     }
".format(version_);

    auto footerText = 
"
struct ktxTexture_vvtbl {} 
struct ktxTexture_protected {}
struct ktxTexture1_private {}
struct ktxTexture2_private {}

alias GLuint = uint;
alias GLenum = uint;
";

    auto generator = new APIEmitter(name)
        .addLoaderGenerator(new DLLLoaderGenerator("KTXLoader", dllName, dllNameDebug))
        .setHeaderText(headerText)
        .setFooterText(footerText)
        .setExcludePrefixes(["Vk", "PFN_Vk", "ktx_uint32_t_SIZE_ASSERT"])
        .setAliasPrefixes(["Ktx", "ktx", "PFNKTX", "khr", "PFNKTEX", "PFNGL", "PFNVOIDFUNCTION"])
        .setTypePrefixes(["Ktx", "ktx", "khr", "_khr", "streamType", "class_id"])
        .setFunctionPrefixes(["ktx", "khr"])
        //.addStdintAliases()
        ;

    string vulkanSdk = environment.get("VULKAN_SDK");
    string ktxDir    = "C:/Temp/KTX-Software-5.0.0-rc1/";

    writefln("Vulkan SDK   : %s", vulkanSdk);
    writefln("KTX directory: %s", ktxDir);

    Config conf = {
        sourceDirectory: "resources/large-tests/",
        targetDirectory: ".target/test-ktx/",
        includeDirectories: [
            vulkanSdk ~ "/Include",
            ktxDir ~ "lib/include",
            ktxDir ~ "external/dfdutils",
        ],
        emitter: generator
    };
    
    EC ec = new EC(conf);

    ec.addCFile("test_ktx.c");
    ec.generate();

    writefln("  Done");
}
