module test_generator.gen_vma;

import std.stdio    : writefln;
import std.process  : environment;
import std.string   : endsWith;

import ec.parse.stmt.Stmt;
import ec.parse.stmt.Typedef;
import ec.all;

import common       : StringBuffer;
import common.utils : getSuffix;

void generateVma() {
    writefln("Generating VMA API...");

    enum version_      = "3.4.0";
    enum name          = "VMA";
    enum dllName       = "vma-%s.dll".format(version_);
    enum dllNameDebug  = "vma-%s-debug.dll".format(version_);

    auto headerText =
"module vma_api;

private import vulkan.api.vulkan_api;

public:

// Vulkan Memory Allocator %s include file converted to D (This is a generated file)
//
// (https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator)
// 
// Generated by Echo-C (https://github.com/pvmoore/echo-c)
// 
// Usage:
//     VMALoader.load();
//     ** 
//     ** Use vma functions here
//     ** 
//     VMALoader.unload();
".format(version_);

    auto generator = new APIEmitter(name)
        .addLoaderGenerator(new DLLLoaderGenerator("VMALoader", dllName, dllNameDebug))
        .setHeaderText(headerText)
        .setFooterText("")
        .setExcludePrefixes(["Vk", "PFN_Vk"])
        .setAliasPrefixes(["Vma", "PFN_vma", "int", "uint"])
        .setTypePrefixes(["Vma"])
        .setFunctionPrefixes(["vma"])
        .setGlobalPrefixes(null)
        ;

    string vulkanSdk = environment.get("VULKAN_SDK");
    writefln("Vulkan SDK: %s", vulkanSdk);

    Config conf = {
        sourceDirectory: "resources/large-tests/",
        targetDirectory: ".target/test-vma/",
        includeDirectories: [
            vulkanSdk ~ "/Include",
            vulkanSdk ~ "/Include/vma/"
        ],
        emitter: generator
    };
    
    EC ec = new EC(conf);

    ec.addCFile("test_vma.c");
    ec.generate();

    writefln("  Done");
}

