module test_generator.gen_vulkan;

import std.stdio    : writefln;
import std.process  : environment;
import std.string   : endsWith;

import ec.parse.stmt.Stmt;
import ec.parse.stmt.Typedef;
import ec.all;

import common       : StringBuffer;
import common.utils : getSuffix;

void generateVulkan() {
    writefln("Generating Vulkan API...");

    enum version_      = "1.4.350.0";
    enum name          = "Vulkan";
    enum dllName       = "vulkan-1.dll";

    auto headerText =
"module vulkan_api;

public:

// Vulkan %s include file converted to D (This is a generated file)
// 
// Generated by Echo-C (https://github.com/pvmoore/echo-c)
// 
// Usage:
//     VulkanLoader.load();
//        vkLoadGlobalCommandFunctions();
//        ** Create your VkInstance here
//        vkLoadInstanceFunctions(instance);
//        ** 
//     VulkanLoader.unload();
".format(version_);

    auto footerText = 
"
enum VK_TRUE                   = 1;
enum VK_FALSE                  = 0;
enum VK_NULL_HANDLE            = null;
enum VK_QUEUE_FAMILY_IGNORED   = ~0U;
enum VK_REMAINING_MIP_LEVELS   = ~0U;
enum VK_REMAINING_ARRAY_LAYERS = ~0U;
enum VK_SUBPASS_EXTERNAL       = ~0U;
enum VK_SHADER_UNUSED_KHR      = ~0U;
enum VK_WHOLE_SIZE             = ~0UL;
";    

    auto globalCommandFunctions = [
        "vkEnumerateInstanceVersion",
        "vkEnumerateInstanceExtensionProperties",
        "vkEnumerateInstanceLayerProperties",
        "vkCreateInstance",
    ];

    auto loader = new class DLLLoaderGenerator {
        this() {
            super(name ~ "Loader", dllName, null);
        }
        override void setFunctionNames(string[] names...) {
            // Ignore the function names passed to us
            super.setFunctionNames(["vkGetInstanceProcAddr"]);
        }
    };
    auto globalCommandFunctionsLoader = new class AbsLoaderGenerator {
        override void setFunctionNames(string[] names...) {
            super.setFunctionNames(globalCommandFunctions);
        }
        override void emitProlog(StringBuffer buf) {
            buf.add("// Load Global Command Functions\n");
            buf.add("void vkLoadGlobalCommandFunctions() {\n");
        }
        override void emitFunctions(StringBuffer buf, string[] functionNames) {
            foreach(f; functionNames) {
                buf.add("\t*(cast(void**)&%s) = vkGetInstanceProcAddr(null, \"%s\");", f, f);
                buf.add(" assert(%s);\n", f);
            }
        }
        override void emitEpilog(StringBuffer buf) {
            buf.add("}\n");
        }
    };
    auto instanceFunctionsLoader = new class AbsLoaderGenerator {
        override void setFunctionNames(string[] names...) {
            super.setFunctionNames(names.filter!(it=>it != "vkGetInstanceProcAddr" && !it.isOneOf(globalCommandFunctions)).array());
        }
        override void emitProlog(StringBuffer buf) {
            buf.add("// Load Instance Functions\n");
            buf.add("void vkLoadInstanceFunctions(VkInstance instance) {\n");
        }
        override void emitFunctions(StringBuffer buf, string[] functionNames) {
            foreach(f; functionNames) {
                buf.add("\t*(cast(void**)&%s) = vkGetInstanceProcAddr(instance, \"%s\");\n", f, f);
            }
        }
        override void emitEpilog(StringBuffer buf) {
            buf.add("}\n");
        }
    };

    auto generator = new APIEmitter(name)
        .addLoaderGenerator(loader)
        .addLoaderGenerator(globalCommandFunctionsLoader)
        .addLoaderGenerator(instanceFunctionsLoader)
        .setHeaderText(headerText)
        .setFooterText(footerText)
        .setExcludePrefixes([])
        .setAliasPrefixes(["Vk", "PFN_vk", "VK", "int", "uint"])
        .setTypePrefixes(["Vk", "VK", "Std"])
        .setFunctionPrefixes(["vk"])
        .setGlobalPrefixes(["VK"])
        ;

    string vulkanSdk = environment.get("VULKAN_SDK");
    writefln("Vulkan SDK: %s", vulkanSdk);

    Config conf = {
        sourceDirectory: "resources/large-tests/",
        targetDirectory: ".target/test-vulkan/",
        includeDirectories: [
            vulkanSdk ~ "/Include",
        ],
        emitter: generator
    };
    
    EC ec = new EC(conf);

    ec.addCFile("test_vulkan.c");
    ec.generate();
    writefln("  Done");
}
